spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: embarkx
    password: embarkx
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: "Hello Order!"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7