spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom_user
      database: ecom_user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"